### ISSUE TITLE
Loading to BQ really slow :(

### ISSUE THREAD

**Issue by samelamin** [appsflyer-dev/spark-bigquery#2]
Hi Folks

I noticed that loading small datasets (df of 400-500 rows) is ridiculously slow (were talking tens of minutes!) 

Is this normal? is there perhaps a config setting I am missing

**Comment by spektom** [comment]
Hi,

Can you provide some sample snippet?

**Comment by samelamin** [comment]
hi @spektom, Apologies! Reading my ticket back I realised I provided zero info! I always find that annoying in issues. so sorry! 


So Ive got a dataframe that purly json

`    var df = sqlContext
      .read
      .json(jsonPath)
      .dropDuplicates()

    df.saveAsBigQueryTable("project-id:dataset-id.table-name")`
 


Theres not much code there really, but its still super slow to save that dataframe

if it helps the table is created with the right schema in seconds. Its just the moving of the data


Maybe it would help if you explain how this data is being moved to BQ using your connector

**Comment by samelamin** [comment]
Ive been doing a bit more digging into this, it seems like the connector is creating a new table for each record on the dataframe. I can see hundreds of new tables in the unique dataset created per spark job

I have a feeling this isn't the intended behaviour

this is further weird behaviour that I am seeing lots of connections created by the factory, presumably creating the tables mentioned

`
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from default credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
17/01/06 11:42:36 INFO BigQueryFactory: Creating BigQuery from given credential.
`

**Comment by spektom** [comment]
Data frame writer opens a new BigQuery session per partition. You can try to reduce number of output partitions, and see whether it helps in your case.

**Comment by samelamin** [comment]
yup that worked a treat! thanks
